/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TheatersIndexRouteImport } from './routes/theaters/index'
import { Route as SpecializationsIndexRouteImport } from './routes/specializations/index'
import { Route as SpacesIndexRouteImport } from './routes/spaces/index'
import { Route as ProductionsIndexRouteImport } from './routes/productions/index'
import { Route as PlaysIndexRouteImport } from './routes/plays/index'
import { Route as AuthorsIndexRouteImport } from './routes/authors/index'
import { Route as SpecializationsNewRouteImport } from './routes/specializations/new'
import { Route as SpecializationsSpecializationIdRouteImport } from './routes/specializations/$specializationId'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as UsersUserIdIndexRouteImport } from './routes/users/$userId/index'
import { Route as TheatersTheaterIdIndexRouteImport } from './routes/theaters/$theaterId/index'
import { Route as SpacesSpaceIdIndexRouteImport } from './routes/spaces/$spaceId/index'
import { Route as ProductionsProductionIdIndexRouteImport } from './routes/productions/$productionId/index'
import { Route as PlaysPlayIdIndexRouteImport } from './routes/plays/$playId/index'
import { Route as AuthorsAuthorIdIndexRouteImport } from './routes/authors/$authorId/index'
import { Route as ProductionsProductionIdRehearsalsRouteImport } from './routes/productions/$productionId/rehearsals'
import { Route as PlaysPlayIdScriptRouteImport } from './routes/plays/$playId/script'
import { Route as PlaysPlayIdCharactersIndexRouteImport } from './routes/plays/$playId/characters/index'
import { Route as PlaysPlayIdActsActIdIndexRouteImport } from './routes/plays/$playId/acts/$actId/index'
import { Route as PlaysPlayIdActsActIdScenesNewRouteImport } from './routes/plays/$playId/acts/$actId/scenes/new'
import { Route as PlaysPlayIdActsActIdScenesSceneIdIndexRouteImport } from './routes/plays/$playId/acts/$actId/scenes/$sceneId/index'
import { Route as PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRouteImport } from './routes/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
import { Route as PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRouteImport } from './routes/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersIndexRoute = TheatersIndexRouteImport.update({
  id: '/theaters/',
  path: '/theaters/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsIndexRoute = SpecializationsIndexRouteImport.update({
  id: '/specializations/',
  path: '/specializations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesIndexRoute = SpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsIndexRoute = ProductionsIndexRouteImport.update({
  id: '/productions/',
  path: '/productions/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysIndexRoute = PlaysIndexRouteImport.update({
  id: '/plays/',
  path: '/plays/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsNewRoute = SpecializationsNewRouteImport.update({
  id: '/specializations/new',
  path: '/specializations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializationsSpecializationIdRoute =
  SpecializationsSpecializationIdRouteImport.update({
    id: '/specializations/$specializationId',
    path: '/specializations/$specializationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheatersTheaterIdIndexRoute = TheatersTheaterIdIndexRouteImport.update({
  id: '/theaters/$theaterId/',
  path: '/theaters/$theaterId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpacesSpaceIdIndexRoute = SpacesSpaceIdIndexRouteImport.update({
  id: '/spaces/$spaceId/',
  path: '/spaces/$spaceId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsProductionIdIndexRoute =
  ProductionsProductionIdIndexRouteImport.update({
    id: '/productions/$productionId/',
    path: '/productions/$productionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdIndexRoute = PlaysPlayIdIndexRouteImport.update({
  id: '/plays/$playId/',
  path: '/plays/$playId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsAuthorIdIndexRoute = AuthorsAuthorIdIndexRouteImport.update({
  id: '/authors/$authorId/',
  path: '/authors/$authorId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionsProductionIdRehearsalsRoute =
  ProductionsProductionIdRehearsalsRouteImport.update({
    id: '/productions/$productionId/rehearsals',
    path: '/productions/$productionId/rehearsals',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdScriptRoute = PlaysPlayIdScriptRouteImport.update({
  id: '/plays/$playId/script',
  path: '/plays/$playId/script',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaysPlayIdCharactersIndexRoute =
  PlaysPlayIdCharactersIndexRouteImport.update({
    id: '/plays/$playId/characters/',
    path: '/plays/$playId/characters/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdActsActIdIndexRoute =
  PlaysPlayIdActsActIdIndexRouteImport.update({
    id: '/plays/$playId/acts/$actId/',
    path: '/plays/$playId/acts/$actId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdActsActIdScenesNewRoute =
  PlaysPlayIdActsActIdScenesNewRouteImport.update({
    id: '/plays/$playId/acts/$actId/scenes/new',
    path: '/plays/$playId/acts/$actId/scenes/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdActsActIdScenesSceneIdIndexRoute =
  PlaysPlayIdActsActIdScenesSceneIdIndexRouteImport.update({
    id: '/plays/$playId/acts/$actId/scenes/$sceneId/',
    path: '/plays/$playId/acts/$actId/scenes/$sceneId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute =
  PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRouteImport.update({
    id: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new',
    path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute =
  PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRouteImport.update(
    {
      id: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/',
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/specializations/$specializationId': typeof SpecializationsSpecializationIdRoute
  '/specializations/new': typeof SpecializationsNewRoute
  '/authors/': typeof AuthorsIndexRoute
  '/plays/': typeof PlaysIndexRoute
  '/productions/': typeof ProductionsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/specializations/': typeof SpecializationsIndexRoute
  '/theaters/': typeof TheatersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/plays/$playId/script': typeof PlaysPlayIdScriptRoute
  '/productions/$productionId/rehearsals': typeof ProductionsProductionIdRehearsalsRoute
  '/authors/$authorId/': typeof AuthorsAuthorIdIndexRoute
  '/plays/$playId/': typeof PlaysPlayIdIndexRoute
  '/productions/$productionId/': typeof ProductionsProductionIdIndexRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/theaters/$theaterId/': typeof TheatersTheaterIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/plays/$playId/characters/': typeof PlaysPlayIdCharactersIndexRoute
  '/plays/$playId/acts/$actId/': typeof PlaysPlayIdActsActIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/new': typeof PlaysPlayIdActsActIdScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/': typeof PlaysPlayIdActsActIdScenesSceneIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/': typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/specializations/$specializationId': typeof SpecializationsSpecializationIdRoute
  '/specializations/new': typeof SpecializationsNewRoute
  '/authors': typeof AuthorsIndexRoute
  '/plays': typeof PlaysIndexRoute
  '/productions': typeof ProductionsIndexRoute
  '/spaces': typeof SpacesIndexRoute
  '/specializations': typeof SpecializationsIndexRoute
  '/theaters': typeof TheatersIndexRoute
  '/users': typeof UsersIndexRoute
  '/plays/$playId/script': typeof PlaysPlayIdScriptRoute
  '/productions/$productionId/rehearsals': typeof ProductionsProductionIdRehearsalsRoute
  '/authors/$authorId': typeof AuthorsAuthorIdIndexRoute
  '/plays/$playId': typeof PlaysPlayIdIndexRoute
  '/productions/$productionId': typeof ProductionsProductionIdIndexRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdIndexRoute
  '/theaters/$theaterId': typeof TheatersTheaterIdIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/plays/$playId/characters': typeof PlaysPlayIdCharactersIndexRoute
  '/plays/$playId/acts/$actId': typeof PlaysPlayIdActsActIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/new': typeof PlaysPlayIdActsActIdScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId': typeof PlaysPlayIdActsActIdScenesSceneIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId': typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/specializations/$specializationId': typeof SpecializationsSpecializationIdRoute
  '/specializations/new': typeof SpecializationsNewRoute
  '/authors/': typeof AuthorsIndexRoute
  '/plays/': typeof PlaysIndexRoute
  '/productions/': typeof ProductionsIndexRoute
  '/spaces/': typeof SpacesIndexRoute
  '/specializations/': typeof SpecializationsIndexRoute
  '/theaters/': typeof TheatersIndexRoute
  '/users/': typeof UsersIndexRoute
  '/plays/$playId/script': typeof PlaysPlayIdScriptRoute
  '/productions/$productionId/rehearsals': typeof ProductionsProductionIdRehearsalsRoute
  '/authors/$authorId/': typeof AuthorsAuthorIdIndexRoute
  '/plays/$playId/': typeof PlaysPlayIdIndexRoute
  '/productions/$productionId/': typeof ProductionsProductionIdIndexRoute
  '/spaces/$spaceId/': typeof SpacesSpaceIdIndexRoute
  '/theaters/$theaterId/': typeof TheatersTheaterIdIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/plays/$playId/characters/': typeof PlaysPlayIdCharactersIndexRoute
  '/plays/$playId/acts/$actId/': typeof PlaysPlayIdActsActIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/new': typeof PlaysPlayIdActsActIdScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/': typeof PlaysPlayIdActsActIdScenesSceneIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/': typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/specializations/$specializationId'
    | '/specializations/new'
    | '/authors/'
    | '/plays/'
    | '/productions/'
    | '/spaces/'
    | '/specializations/'
    | '/theaters/'
    | '/users/'
    | '/plays/$playId/script'
    | '/productions/$productionId/rehearsals'
    | '/authors/$authorId/'
    | '/plays/$playId/'
    | '/productions/$productionId/'
    | '/spaces/$spaceId/'
    | '/theaters/$theaterId/'
    | '/users/$userId/'
    | '/plays/$playId/characters/'
    | '/plays/$playId/acts/$actId/'
    | '/plays/$playId/acts/$actId/scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/callback'
    | '/specializations/$specializationId'
    | '/specializations/new'
    | '/authors'
    | '/plays'
    | '/productions'
    | '/spaces'
    | '/specializations'
    | '/theaters'
    | '/users'
    | '/plays/$playId/script'
    | '/productions/$productionId/rehearsals'
    | '/authors/$authorId'
    | '/plays/$playId'
    | '/productions/$productionId'
    | '/spaces/$spaceId'
    | '/theaters/$theaterId'
    | '/users/$userId'
    | '/plays/$playId/characters'
    | '/plays/$playId/acts/$actId'
    | '/plays/$playId/acts/$actId/scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/callback'
    | '/specializations/$specializationId'
    | '/specializations/new'
    | '/authors/'
    | '/plays/'
    | '/productions/'
    | '/spaces/'
    | '/specializations/'
    | '/theaters/'
    | '/users/'
    | '/plays/$playId/script'
    | '/productions/$productionId/rehearsals'
    | '/authors/$authorId/'
    | '/plays/$playId/'
    | '/productions/$productionId/'
    | '/spaces/$spaceId/'
    | '/theaters/$theaterId/'
    | '/users/$userId/'
    | '/plays/$playId/characters/'
    | '/plays/$playId/acts/$actId/'
    | '/plays/$playId/acts/$actId/scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  SpecializationsSpecializationIdRoute: typeof SpecializationsSpecializationIdRoute
  SpecializationsNewRoute: typeof SpecializationsNewRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  PlaysIndexRoute: typeof PlaysIndexRoute
  ProductionsIndexRoute: typeof ProductionsIndexRoute
  SpacesIndexRoute: typeof SpacesIndexRoute
  SpecializationsIndexRoute: typeof SpecializationsIndexRoute
  TheatersIndexRoute: typeof TheatersIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  PlaysPlayIdScriptRoute: typeof PlaysPlayIdScriptRoute
  ProductionsProductionIdRehearsalsRoute: typeof ProductionsProductionIdRehearsalsRoute
  AuthorsAuthorIdIndexRoute: typeof AuthorsAuthorIdIndexRoute
  PlaysPlayIdIndexRoute: typeof PlaysPlayIdIndexRoute
  ProductionsProductionIdIndexRoute: typeof ProductionsProductionIdIndexRoute
  SpacesSpaceIdIndexRoute: typeof SpacesSpaceIdIndexRoute
  TheatersTheaterIdIndexRoute: typeof TheatersTheaterIdIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  PlaysPlayIdCharactersIndexRoute: typeof PlaysPlayIdCharactersIndexRoute
  PlaysPlayIdActsActIdIndexRoute: typeof PlaysPlayIdActsActIdIndexRoute
  PlaysPlayIdActsActIdScenesNewRoute: typeof PlaysPlayIdActsActIdScenesNewRoute
  PlaysPlayIdActsActIdScenesSceneIdIndexRoute: typeof PlaysPlayIdActsActIdScenesSceneIdIndexRoute
  PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute: typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute: typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/': {
      id: '/theaters/'
      path: '/theaters'
      fullPath: '/theaters/'
      preLoaderRoute: typeof TheatersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations/': {
      id: '/specializations/'
      path: '/specializations'
      fullPath: '/specializations/'
      preLoaderRoute: typeof SpecializationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/': {
      id: '/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/': {
      id: '/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof ProductionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/': {
      id: '/plays/'
      path: '/plays'
      fullPath: '/plays/'
      preLoaderRoute: typeof PlaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations/new': {
      id: '/specializations/new'
      path: '/specializations/new'
      fullPath: '/specializations/new'
      preLoaderRoute: typeof SpecializationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specializations/$specializationId': {
      id: '/specializations/$specializationId'
      path: '/specializations/$specializationId'
      fullPath: '/specializations/$specializationId'
      preLoaderRoute: typeof SpecializationsSpecializationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theaters/$theaterId/': {
      id: '/theaters/$theaterId/'
      path: '/theaters/$theaterId'
      fullPath: '/theaters/$theaterId/'
      preLoaderRoute: typeof TheatersTheaterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spaces/$spaceId/': {
      id: '/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof SpacesSpaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/$productionId/': {
      id: '/productions/$productionId/'
      path: '/productions/$productionId'
      fullPath: '/productions/$productionId/'
      preLoaderRoute: typeof ProductionsProductionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/': {
      id: '/plays/$playId/'
      path: '/plays/$playId'
      fullPath: '/plays/$playId/'
      preLoaderRoute: typeof PlaysPlayIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$authorId/': {
      id: '/authors/$authorId/'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId/'
      preLoaderRoute: typeof AuthorsAuthorIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productions/$productionId/rehearsals': {
      id: '/productions/$productionId/rehearsals'
      path: '/productions/$productionId/rehearsals'
      fullPath: '/productions/$productionId/rehearsals'
      preLoaderRoute: typeof ProductionsProductionIdRehearsalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/script': {
      id: '/plays/$playId/script'
      path: '/plays/$playId/script'
      fullPath: '/plays/$playId/script'
      preLoaderRoute: typeof PlaysPlayIdScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/characters/': {
      id: '/plays/$playId/characters/'
      path: '/plays/$playId/characters'
      fullPath: '/plays/$playId/characters/'
      preLoaderRoute: typeof PlaysPlayIdCharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/acts/$actId/': {
      id: '/plays/$playId/acts/$actId/'
      path: '/plays/$playId/acts/$actId'
      fullPath: '/plays/$playId/acts/$actId/'
      preLoaderRoute: typeof PlaysPlayIdActsActIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/acts/$actId/scenes/new': {
      id: '/plays/$playId/acts/$actId/scenes/new'
      path: '/plays/$playId/acts/$actId/scenes/new'
      fullPath: '/plays/$playId/acts/$actId/scenes/new'
      preLoaderRoute: typeof PlaysPlayIdActsActIdScenesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/acts/$actId/scenes/$sceneId/': {
      id: '/plays/$playId/acts/$actId/scenes/$sceneId/'
      path: '/plays/$playId/acts/$actId/scenes/$sceneId'
      fullPath: '/plays/$playId/acts/$actId/scenes/$sceneId/'
      preLoaderRoute: typeof PlaysPlayIdActsActIdScenesSceneIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': {
      id: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
      fullPath: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
      preLoaderRoute: typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/': {
      id: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId'
      fullPath: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
      preLoaderRoute: typeof PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  SpecializationsSpecializationIdRoute: SpecializationsSpecializationIdRoute,
  SpecializationsNewRoute: SpecializationsNewRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  PlaysIndexRoute: PlaysIndexRoute,
  ProductionsIndexRoute: ProductionsIndexRoute,
  SpacesIndexRoute: SpacesIndexRoute,
  SpecializationsIndexRoute: SpecializationsIndexRoute,
  TheatersIndexRoute: TheatersIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  PlaysPlayIdScriptRoute: PlaysPlayIdScriptRoute,
  ProductionsProductionIdRehearsalsRoute:
    ProductionsProductionIdRehearsalsRoute,
  AuthorsAuthorIdIndexRoute: AuthorsAuthorIdIndexRoute,
  PlaysPlayIdIndexRoute: PlaysPlayIdIndexRoute,
  ProductionsProductionIdIndexRoute: ProductionsProductionIdIndexRoute,
  SpacesSpaceIdIndexRoute: SpacesSpaceIdIndexRoute,
  TheatersTheaterIdIndexRoute: TheatersTheaterIdIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  PlaysPlayIdCharactersIndexRoute: PlaysPlayIdCharactersIndexRoute,
  PlaysPlayIdActsActIdIndexRoute: PlaysPlayIdActsActIdIndexRoute,
  PlaysPlayIdActsActIdScenesNewRoute: PlaysPlayIdActsActIdScenesNewRoute,
  PlaysPlayIdActsActIdScenesSceneIdIndexRoute:
    PlaysPlayIdActsActIdScenesSceneIdIndexRoute,
  PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute:
    PlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute,
  PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute:
    PlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
