/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FreeRouteImport } from './routes/free'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreeIndexRouteImport } from './routes/free/index'
import { Route as FreeWordCloudRouteImport } from './routes/free/word-cloud'
import { Route as FreePartScriptsRouteImport } from './routes/free/part-scripts'
import { Route as FreeDoublingRouteImport } from './routes/free/doubling'
import { Route as FreeCutRouteImport } from './routes/free/cut'
import { Route as FreeCastingRouteImport } from './routes/free/casting'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as PublicHelpRouteImport } from './routes/_public/help'
import { Route as PublicGettingStartedRouteImport } from './routes/_public/getting-started'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTheatersIndexRouteImport } from './routes/_authenticated/theaters/index'
import { Route as AuthenticatedSpecializationsIndexRouteImport } from './routes/_authenticated/specializations/index'
import { Route as AuthenticatedSpacesIndexRouteImport } from './routes/_authenticated/spaces/index'
import { Route as AuthenticatedProductionsIndexRouteImport } from './routes/_authenticated/productions/index'
import { Route as AuthenticatedPlaysIndexRouteImport } from './routes/_authenticated/plays/index'
import { Route as AuthenticatedAuthorsIndexRouteImport } from './routes/_authenticated/authors/index'
import { Route as AuthenticatedTheatersNewRouteImport } from './routes/_authenticated/theaters/new'
import { Route as AuthenticatedSpecializationsNewRouteImport } from './routes/_authenticated/specializations/new'
import { Route as AuthenticatedSpecializationsSpecializationIdRouteImport } from './routes/_authenticated/specializations/$specializationId'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users/$userId/index'
import { Route as AuthenticatedTheatersTheaterIdIndexRouteImport } from './routes/_authenticated/theaters/$theaterId/index'
import { Route as AuthenticatedSpacesSpaceIdIndexRouteImport } from './routes/_authenticated/spaces/$spaceId/index'
import { Route as AuthenticatedProductionsProductionIdIndexRouteImport } from './routes/_authenticated/productions/$productionId/index'
import { Route as AuthenticatedPlaysPlayIdIndexRouteImport } from './routes/_authenticated/plays/$playId/index'
import { Route as AuthenticatedAuthorsAuthorIdIndexRouteImport } from './routes/_authenticated/authors/$authorId/index'
import { Route as AuthenticatedProductionsProductionIdSetDesignRouteImport } from './routes/_authenticated/productions/$productionId/set-design'
import { Route as AuthenticatedProductionsProductionIdRehearsalsRouteImport } from './routes/_authenticated/productions/$productionId/rehearsals'
import { Route as AuthenticatedProductionsProductionIdDoublingChartsRouteImport } from './routes/_authenticated/productions/$productionId/doubling-charts'
import { Route as AuthenticatedPlaysPlayIdWordCloudsRouteImport } from './routes/_authenticated/plays/$playId/word-clouds'
import { Route as AuthenticatedPlaysPlayIdScriptRouteImport } from './routes/_authenticated/plays/$playId/script'
import { Route as AuthenticatedPlaysPlayIdPartScriptsRouteImport } from './routes/_authenticated/plays/$playId/part-scripts'
import { Route as AuthenticatedPlaysPlayIdActsActIdIndexRouteImport } from './routes/_authenticated/plays/$playId/acts/$actId/index'
import { Route as AuthenticatedPlaysPlayIdActsActIdScenesNewRouteImport } from './routes/_authenticated/plays/$playId/acts/$actId/scenes/new'
import { Route as AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRouteImport } from './routes/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/index'
import { Route as AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRouteImport } from './routes/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
import { Route as AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRouteImport } from './routes/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/index'

const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeIndexRoute = FreeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreeRoute,
} as any)
const FreeWordCloudRoute = FreeWordCloudRouteImport.update({
  id: '/word-cloud',
  path: '/word-cloud',
  getParentRoute: () => FreeRoute,
} as any)
const FreePartScriptsRoute = FreePartScriptsRouteImport.update({
  id: '/part-scripts',
  path: '/part-scripts',
  getParentRoute: () => FreeRoute,
} as any)
const FreeDoublingRoute = FreeDoublingRouteImport.update({
  id: '/doubling',
  path: '/doubling',
  getParentRoute: () => FreeRoute,
} as any)
const FreeCutRoute = FreeCutRouteImport.update({
  id: '/cut',
  path: '/cut',
  getParentRoute: () => FreeRoute,
} as any)
const FreeCastingRoute = FreeCastingRouteImport.update({
  id: '/casting',
  path: '/casting',
  getParentRoute: () => FreeRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHelpRoute = PublicHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGettingStartedRoute = PublicGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTheatersIndexRoute =
  AuthenticatedTheatersIndexRouteImport.update({
    id: '/theaters/',
    path: '/theaters/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpecializationsIndexRoute =
  AuthenticatedSpecializationsIndexRouteImport.update({
    id: '/specializations/',
    path: '/specializations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesIndexRoute =
  AuthenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionsIndexRoute =
  AuthenticatedProductionsIndexRouteImport.update({
    id: '/productions/',
    path: '/productions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysIndexRoute = AuthenticatedPlaysIndexRouteImport.update({
  id: '/plays/',
  path: '/plays/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthorsIndexRoute =
  AuthenticatedAuthorsIndexRouteImport.update({
    id: '/authors/',
    path: '/authors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTheatersNewRoute =
  AuthenticatedTheatersNewRouteImport.update({
    id: '/theaters/new',
    path: '/theaters/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpecializationsNewRoute =
  AuthenticatedSpecializationsNewRouteImport.update({
    id: '/specializations/new',
    path: '/specializations/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpecializationsSpecializationIdRoute =
  AuthenticatedSpecializationsSpecializationIdRouteImport.update({
    id: '/specializations/$specializationId',
    path: '/specializations/$specializationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTheatersTheaterIdIndexRoute =
  AuthenticatedTheatersTheaterIdIndexRouteImport.update({
    id: '/theaters/$theaterId/',
    path: '/theaters/$theaterId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSpacesSpaceIdIndexRoute =
  AuthenticatedSpacesSpaceIdIndexRouteImport.update({
    id: '/spaces/$spaceId/',
    path: '/spaces/$spaceId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionsProductionIdIndexRoute =
  AuthenticatedProductionsProductionIdIndexRouteImport.update({
    id: '/productions/$productionId/',
    path: '/productions/$productionId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdIndexRoute =
  AuthenticatedPlaysPlayIdIndexRouteImport.update({
    id: '/plays/$playId/',
    path: '/plays/$playId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuthorsAuthorIdIndexRoute =
  AuthenticatedAuthorsAuthorIdIndexRouteImport.update({
    id: '/authors/$authorId/',
    path: '/authors/$authorId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionsProductionIdSetDesignRoute =
  AuthenticatedProductionsProductionIdSetDesignRouteImport.update({
    id: '/productions/$productionId/set-design',
    path: '/productions/$productionId/set-design',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionsProductionIdRehearsalsRoute =
  AuthenticatedProductionsProductionIdRehearsalsRouteImport.update({
    id: '/productions/$productionId/rehearsals',
    path: '/productions/$productionId/rehearsals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductionsProductionIdDoublingChartsRoute =
  AuthenticatedProductionsProductionIdDoublingChartsRouteImport.update({
    id: '/productions/$productionId/doubling-charts',
    path: '/productions/$productionId/doubling-charts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdWordCloudsRoute =
  AuthenticatedPlaysPlayIdWordCloudsRouteImport.update({
    id: '/plays/$playId/word-clouds',
    path: '/plays/$playId/word-clouds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdScriptRoute =
  AuthenticatedPlaysPlayIdScriptRouteImport.update({
    id: '/plays/$playId/script',
    path: '/plays/$playId/script',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdPartScriptsRoute =
  AuthenticatedPlaysPlayIdPartScriptsRouteImport.update({
    id: '/plays/$playId/part-scripts',
    path: '/plays/$playId/part-scripts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdActsActIdIndexRoute =
  AuthenticatedPlaysPlayIdActsActIdIndexRouteImport.update({
    id: '/plays/$playId/acts/$actId/',
    path: '/plays/$playId/acts/$actId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdActsActIdScenesNewRoute =
  AuthenticatedPlaysPlayIdActsActIdScenesNewRouteImport.update({
    id: '/plays/$playId/acts/$actId/scenes/new',
    path: '/plays/$playId/acts/$actId/scenes/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute =
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRouteImport.update({
    id: '/plays/$playId/acts/$actId/scenes/$sceneId/',
    path: '/plays/$playId/acts/$actId/scenes/$sceneId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute =
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRouteImport.update(
    {
      id: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new',
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )
const AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute =
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRouteImport.update(
    {
      id: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/',
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/free': typeof FreeRouteWithChildren
  '/account': typeof AuthenticatedAccountRoute
  '/faq': typeof PublicFaqRoute
  '/getting-started': typeof PublicGettingStartedRoute
  '/help': typeof PublicHelpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/free/casting': typeof FreeCastingRoute
  '/free/cut': typeof FreeCutRoute
  '/free/doubling': typeof FreeDoublingRoute
  '/free/part-scripts': typeof FreePartScriptsRoute
  '/free/word-cloud': typeof FreeWordCloudRoute
  '/free/': typeof FreeIndexRoute
  '/specializations/$specializationId': typeof AuthenticatedSpecializationsSpecializationIdRoute
  '/specializations/new': typeof AuthenticatedSpecializationsNewRoute
  '/theaters/new': typeof AuthenticatedTheatersNewRoute
  '/authors/': typeof AuthenticatedAuthorsIndexRoute
  '/plays/': typeof AuthenticatedPlaysIndexRoute
  '/productions/': typeof AuthenticatedProductionsIndexRoute
  '/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/specializations/': typeof AuthenticatedSpecializationsIndexRoute
  '/theaters/': typeof AuthenticatedTheatersIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/plays/$playId/part-scripts': typeof AuthenticatedPlaysPlayIdPartScriptsRoute
  '/plays/$playId/script': typeof AuthenticatedPlaysPlayIdScriptRoute
  '/plays/$playId/word-clouds': typeof AuthenticatedPlaysPlayIdWordCloudsRoute
  '/productions/$productionId/doubling-charts': typeof AuthenticatedProductionsProductionIdDoublingChartsRoute
  '/productions/$productionId/rehearsals': typeof AuthenticatedProductionsProductionIdRehearsalsRoute
  '/productions/$productionId/set-design': typeof AuthenticatedProductionsProductionIdSetDesignRoute
  '/authors/$authorId/': typeof AuthenticatedAuthorsAuthorIdIndexRoute
  '/plays/$playId/': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/productions/$productionId/': typeof AuthenticatedProductionsProductionIdIndexRoute
  '/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/theaters/$theaterId/': typeof AuthenticatedTheatersTheaterIdIndexRoute
  '/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/plays/$playId/acts/$actId/': typeof AuthenticatedPlaysPlayIdActsActIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/new': typeof AuthenticatedPlaysPlayIdActsActIdScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AuthenticatedAccountRoute
  '/faq': typeof PublicFaqRoute
  '/getting-started': typeof PublicGettingStartedRoute
  '/help': typeof PublicHelpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/free/casting': typeof FreeCastingRoute
  '/free/cut': typeof FreeCutRoute
  '/free/doubling': typeof FreeDoublingRoute
  '/free/part-scripts': typeof FreePartScriptsRoute
  '/free/word-cloud': typeof FreeWordCloudRoute
  '/free': typeof FreeIndexRoute
  '/specializations/$specializationId': typeof AuthenticatedSpecializationsSpecializationIdRoute
  '/specializations/new': typeof AuthenticatedSpecializationsNewRoute
  '/theaters/new': typeof AuthenticatedTheatersNewRoute
  '/authors': typeof AuthenticatedAuthorsIndexRoute
  '/plays': typeof AuthenticatedPlaysIndexRoute
  '/productions': typeof AuthenticatedProductionsIndexRoute
  '/spaces': typeof AuthenticatedSpacesIndexRoute
  '/specializations': typeof AuthenticatedSpecializationsIndexRoute
  '/theaters': typeof AuthenticatedTheatersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/plays/$playId/part-scripts': typeof AuthenticatedPlaysPlayIdPartScriptsRoute
  '/plays/$playId/script': typeof AuthenticatedPlaysPlayIdScriptRoute
  '/plays/$playId/word-clouds': typeof AuthenticatedPlaysPlayIdWordCloudsRoute
  '/productions/$productionId/doubling-charts': typeof AuthenticatedProductionsProductionIdDoublingChartsRoute
  '/productions/$productionId/rehearsals': typeof AuthenticatedProductionsProductionIdRehearsalsRoute
  '/productions/$productionId/set-design': typeof AuthenticatedProductionsProductionIdSetDesignRoute
  '/authors/$authorId': typeof AuthenticatedAuthorsAuthorIdIndexRoute
  '/plays/$playId': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/productions/$productionId': typeof AuthenticatedProductionsProductionIdIndexRoute
  '/spaces/$spaceId': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/theaters/$theaterId': typeof AuthenticatedTheatersTheaterIdIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
  '/plays/$playId/acts/$actId': typeof AuthenticatedPlaysPlayIdActsActIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/new': typeof AuthenticatedPlaysPlayIdActsActIdScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/about': typeof AboutRoute
  '/free': typeof FreeRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/getting-started': typeof PublicGettingStartedRoute
  '/_public/help': typeof PublicHelpRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/free/casting': typeof FreeCastingRoute
  '/free/cut': typeof FreeCutRoute
  '/free/doubling': typeof FreeDoublingRoute
  '/free/part-scripts': typeof FreePartScriptsRoute
  '/free/word-cloud': typeof FreeWordCloudRoute
  '/free/': typeof FreeIndexRoute
  '/_authenticated/specializations/$specializationId': typeof AuthenticatedSpecializationsSpecializationIdRoute
  '/_authenticated/specializations/new': typeof AuthenticatedSpecializationsNewRoute
  '/_authenticated/theaters/new': typeof AuthenticatedTheatersNewRoute
  '/_authenticated/authors/': typeof AuthenticatedAuthorsIndexRoute
  '/_authenticated/plays/': typeof AuthenticatedPlaysIndexRoute
  '/_authenticated/productions/': typeof AuthenticatedProductionsIndexRoute
  '/_authenticated/spaces/': typeof AuthenticatedSpacesIndexRoute
  '/_authenticated/specializations/': typeof AuthenticatedSpecializationsIndexRoute
  '/_authenticated/theaters/': typeof AuthenticatedTheatersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/plays/$playId/part-scripts': typeof AuthenticatedPlaysPlayIdPartScriptsRoute
  '/_authenticated/plays/$playId/script': typeof AuthenticatedPlaysPlayIdScriptRoute
  '/_authenticated/plays/$playId/word-clouds': typeof AuthenticatedPlaysPlayIdWordCloudsRoute
  '/_authenticated/productions/$productionId/doubling-charts': typeof AuthenticatedProductionsProductionIdDoublingChartsRoute
  '/_authenticated/productions/$productionId/rehearsals': typeof AuthenticatedProductionsProductionIdRehearsalsRoute
  '/_authenticated/productions/$productionId/set-design': typeof AuthenticatedProductionsProductionIdSetDesignRoute
  '/_authenticated/authors/$authorId/': typeof AuthenticatedAuthorsAuthorIdIndexRoute
  '/_authenticated/plays/$playId/': typeof AuthenticatedPlaysPlayIdIndexRoute
  '/_authenticated/productions/$productionId/': typeof AuthenticatedProductionsProductionIdIndexRoute
  '/_authenticated/spaces/$spaceId/': typeof AuthenticatedSpacesSpaceIdIndexRoute
  '/_authenticated/theaters/$theaterId/': typeof AuthenticatedTheatersTheaterIdIndexRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
  '/_authenticated/plays/$playId/acts/$actId/': typeof AuthenticatedPlaysPlayIdActsActIdIndexRoute
  '/_authenticated/plays/$playId/acts/$actId/scenes/new': typeof AuthenticatedPlaysPlayIdActsActIdScenesNewRoute
  '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute
  '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/': typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/free'
    | '/account'
    | '/faq'
    | '/getting-started'
    | '/help'
    | '/auth/callback'
    | '/free/casting'
    | '/free/cut'
    | '/free/doubling'
    | '/free/part-scripts'
    | '/free/word-cloud'
    | '/free/'
    | '/specializations/$specializationId'
    | '/specializations/new'
    | '/theaters/new'
    | '/authors/'
    | '/plays/'
    | '/productions/'
    | '/spaces/'
    | '/specializations/'
    | '/theaters/'
    | '/users/'
    | '/plays/$playId/part-scripts'
    | '/plays/$playId/script'
    | '/plays/$playId/word-clouds'
    | '/productions/$productionId/doubling-charts'
    | '/productions/$productionId/rehearsals'
    | '/productions/$productionId/set-design'
    | '/authors/$authorId/'
    | '/plays/$playId/'
    | '/productions/$productionId/'
    | '/spaces/$spaceId/'
    | '/theaters/$theaterId/'
    | '/users/$userId/'
    | '/plays/$playId/acts/$actId/'
    | '/plays/$playId/acts/$actId/scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/faq'
    | '/getting-started'
    | '/help'
    | '/auth/callback'
    | '/free/casting'
    | '/free/cut'
    | '/free/doubling'
    | '/free/part-scripts'
    | '/free/word-cloud'
    | '/free'
    | '/specializations/$specializationId'
    | '/specializations/new'
    | '/theaters/new'
    | '/authors'
    | '/plays'
    | '/productions'
    | '/spaces'
    | '/specializations'
    | '/theaters'
    | '/users'
    | '/plays/$playId/part-scripts'
    | '/plays/$playId/script'
    | '/plays/$playId/word-clouds'
    | '/productions/$productionId/doubling-charts'
    | '/productions/$productionId/rehearsals'
    | '/productions/$productionId/set-design'
    | '/authors/$authorId'
    | '/plays/$playId'
    | '/productions/$productionId'
    | '/spaces/$spaceId'
    | '/theaters/$theaterId'
    | '/users/$userId'
    | '/plays/$playId/acts/$actId'
    | '/plays/$playId/acts/$actId/scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
    | '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/about'
    | '/free'
    | '/_authenticated/account'
    | '/_public/faq'
    | '/_public/getting-started'
    | '/_public/help'
    | '/auth/callback'
    | '/free/casting'
    | '/free/cut'
    | '/free/doubling'
    | '/free/part-scripts'
    | '/free/word-cloud'
    | '/free/'
    | '/_authenticated/specializations/$specializationId'
    | '/_authenticated/specializations/new'
    | '/_authenticated/theaters/new'
    | '/_authenticated/authors/'
    | '/_authenticated/plays/'
    | '/_authenticated/productions/'
    | '/_authenticated/spaces/'
    | '/_authenticated/specializations/'
    | '/_authenticated/theaters/'
    | '/_authenticated/users/'
    | '/_authenticated/plays/$playId/part-scripts'
    | '/_authenticated/plays/$playId/script'
    | '/_authenticated/plays/$playId/word-clouds'
    | '/_authenticated/productions/$productionId/doubling-charts'
    | '/_authenticated/productions/$productionId/rehearsals'
    | '/_authenticated/productions/$productionId/set-design'
    | '/_authenticated/authors/$authorId/'
    | '/_authenticated/plays/$playId/'
    | '/_authenticated/productions/$productionId/'
    | '/_authenticated/spaces/$spaceId/'
    | '/_authenticated/theaters/$theaterId/'
    | '/_authenticated/users/$userId/'
    | '/_authenticated/plays/$playId/acts/$actId/'
    | '/_authenticated/plays/$playId/acts/$actId/scenes/new'
    | '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/'
    | '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
    | '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AboutRoute: typeof AboutRoute
  FreeRoute: typeof FreeRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free/': {
      id: '/free/'
      path: '/'
      fullPath: '/free/'
      preLoaderRoute: typeof FreeIndexRouteImport
      parentRoute: typeof FreeRoute
    }
    '/free/word-cloud': {
      id: '/free/word-cloud'
      path: '/word-cloud'
      fullPath: '/free/word-cloud'
      preLoaderRoute: typeof FreeWordCloudRouteImport
      parentRoute: typeof FreeRoute
    }
    '/free/part-scripts': {
      id: '/free/part-scripts'
      path: '/part-scripts'
      fullPath: '/free/part-scripts'
      preLoaderRoute: typeof FreePartScriptsRouteImport
      parentRoute: typeof FreeRoute
    }
    '/free/doubling': {
      id: '/free/doubling'
      path: '/doubling'
      fullPath: '/free/doubling'
      preLoaderRoute: typeof FreeDoublingRouteImport
      parentRoute: typeof FreeRoute
    }
    '/free/cut': {
      id: '/free/cut'
      path: '/cut'
      fullPath: '/free/cut'
      preLoaderRoute: typeof FreeCutRouteImport
      parentRoute: typeof FreeRoute
    }
    '/free/casting': {
      id: '/free/casting'
      path: '/casting'
      fullPath: '/free/casting'
      preLoaderRoute: typeof FreeCastingRouteImport
      parentRoute: typeof FreeRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/help': {
      id: '/_public/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof PublicHelpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/getting-started': {
      id: '/_public/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof PublicGettingStartedRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/theaters/': {
      id: '/_authenticated/theaters/'
      path: '/theaters'
      fullPath: '/theaters/'
      preLoaderRoute: typeof AuthenticatedTheatersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/specializations/': {
      id: '/_authenticated/specializations/'
      path: '/specializations'
      fullPath: '/specializations/'
      preLoaderRoute: typeof AuthenticatedSpecializationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/': {
      id: '/_authenticated/spaces/'
      path: '/spaces'
      fullPath: '/spaces/'
      preLoaderRoute: typeof AuthenticatedSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productions/': {
      id: '/_authenticated/productions/'
      path: '/productions'
      fullPath: '/productions/'
      preLoaderRoute: typeof AuthenticatedProductionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/': {
      id: '/_authenticated/plays/'
      path: '/plays'
      fullPath: '/plays/'
      preLoaderRoute: typeof AuthenticatedPlaysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authors/': {
      id: '/_authenticated/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthenticatedAuthorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/theaters/new': {
      id: '/_authenticated/theaters/new'
      path: '/theaters/new'
      fullPath: '/theaters/new'
      preLoaderRoute: typeof AuthenticatedTheatersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/specializations/new': {
      id: '/_authenticated/specializations/new'
      path: '/specializations/new'
      fullPath: '/specializations/new'
      preLoaderRoute: typeof AuthenticatedSpecializationsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/specializations/$specializationId': {
      id: '/_authenticated/specializations/$specializationId'
      path: '/specializations/$specializationId'
      fullPath: '/specializations/$specializationId'
      preLoaderRoute: typeof AuthenticatedSpecializationsSpecializationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/theaters/$theaterId/': {
      id: '/_authenticated/theaters/$theaterId/'
      path: '/theaters/$theaterId'
      fullPath: '/theaters/$theaterId/'
      preLoaderRoute: typeof AuthenticatedTheatersTheaterIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spaces/$spaceId/': {
      id: '/_authenticated/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId/'
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productions/$productionId/': {
      id: '/_authenticated/productions/$productionId/'
      path: '/productions/$productionId'
      fullPath: '/productions/$productionId/'
      preLoaderRoute: typeof AuthenticatedProductionsProductionIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/': {
      id: '/_authenticated/plays/$playId/'
      path: '/plays/$playId'
      fullPath: '/plays/$playId/'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/authors/$authorId/': {
      id: '/_authenticated/authors/$authorId/'
      path: '/authors/$authorId'
      fullPath: '/authors/$authorId/'
      preLoaderRoute: typeof AuthenticatedAuthorsAuthorIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productions/$productionId/set-design': {
      id: '/_authenticated/productions/$productionId/set-design'
      path: '/productions/$productionId/set-design'
      fullPath: '/productions/$productionId/set-design'
      preLoaderRoute: typeof AuthenticatedProductionsProductionIdSetDesignRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productions/$productionId/rehearsals': {
      id: '/_authenticated/productions/$productionId/rehearsals'
      path: '/productions/$productionId/rehearsals'
      fullPath: '/productions/$productionId/rehearsals'
      preLoaderRoute: typeof AuthenticatedProductionsProductionIdRehearsalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/productions/$productionId/doubling-charts': {
      id: '/_authenticated/productions/$productionId/doubling-charts'
      path: '/productions/$productionId/doubling-charts'
      fullPath: '/productions/$productionId/doubling-charts'
      preLoaderRoute: typeof AuthenticatedProductionsProductionIdDoublingChartsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/word-clouds': {
      id: '/_authenticated/plays/$playId/word-clouds'
      path: '/plays/$playId/word-clouds'
      fullPath: '/plays/$playId/word-clouds'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdWordCloudsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/script': {
      id: '/_authenticated/plays/$playId/script'
      path: '/plays/$playId/script'
      fullPath: '/plays/$playId/script'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdScriptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/part-scripts': {
      id: '/_authenticated/plays/$playId/part-scripts'
      path: '/plays/$playId/part-scripts'
      fullPath: '/plays/$playId/part-scripts'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdPartScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/acts/$actId/': {
      id: '/_authenticated/plays/$playId/acts/$actId/'
      path: '/plays/$playId/acts/$actId'
      fullPath: '/plays/$playId/acts/$actId/'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdActsActIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/acts/$actId/scenes/new': {
      id: '/_authenticated/plays/$playId/acts/$actId/scenes/new'
      path: '/plays/$playId/acts/$actId/scenes/new'
      fullPath: '/plays/$playId/acts/$actId/scenes/new'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/': {
      id: '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/'
      path: '/plays/$playId/acts/$actId/scenes/$sceneId'
      fullPath: '/plays/$playId/acts/$actId/scenes/$sceneId/'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new': {
      id: '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
      fullPath: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/new'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/': {
      id: '/_authenticated/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
      path: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId'
      fullPath: '/plays/$playId/acts/$actId/scenes/$sceneId/french-scenes/$frenchSceneId/'
      preLoaderRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedSpecializationsSpecializationIdRoute: typeof AuthenticatedSpecializationsSpecializationIdRoute
  AuthenticatedSpecializationsNewRoute: typeof AuthenticatedSpecializationsNewRoute
  AuthenticatedTheatersNewRoute: typeof AuthenticatedTheatersNewRoute
  AuthenticatedAuthorsIndexRoute: typeof AuthenticatedAuthorsIndexRoute
  AuthenticatedPlaysIndexRoute: typeof AuthenticatedPlaysIndexRoute
  AuthenticatedProductionsIndexRoute: typeof AuthenticatedProductionsIndexRoute
  AuthenticatedSpacesIndexRoute: typeof AuthenticatedSpacesIndexRoute
  AuthenticatedSpecializationsIndexRoute: typeof AuthenticatedSpecializationsIndexRoute
  AuthenticatedTheatersIndexRoute: typeof AuthenticatedTheatersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedPlaysPlayIdPartScriptsRoute: typeof AuthenticatedPlaysPlayIdPartScriptsRoute
  AuthenticatedPlaysPlayIdScriptRoute: typeof AuthenticatedPlaysPlayIdScriptRoute
  AuthenticatedPlaysPlayIdWordCloudsRoute: typeof AuthenticatedPlaysPlayIdWordCloudsRoute
  AuthenticatedProductionsProductionIdDoublingChartsRoute: typeof AuthenticatedProductionsProductionIdDoublingChartsRoute
  AuthenticatedProductionsProductionIdRehearsalsRoute: typeof AuthenticatedProductionsProductionIdRehearsalsRoute
  AuthenticatedProductionsProductionIdSetDesignRoute: typeof AuthenticatedProductionsProductionIdSetDesignRoute
  AuthenticatedAuthorsAuthorIdIndexRoute: typeof AuthenticatedAuthorsAuthorIdIndexRoute
  AuthenticatedPlaysPlayIdIndexRoute: typeof AuthenticatedPlaysPlayIdIndexRoute
  AuthenticatedProductionsProductionIdIndexRoute: typeof AuthenticatedProductionsProductionIdIndexRoute
  AuthenticatedSpacesSpaceIdIndexRoute: typeof AuthenticatedSpacesSpaceIdIndexRoute
  AuthenticatedTheatersTheaterIdIndexRoute: typeof AuthenticatedTheatersTheaterIdIndexRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
  AuthenticatedPlaysPlayIdActsActIdIndexRoute: typeof AuthenticatedPlaysPlayIdActsActIdIndexRoute
  AuthenticatedPlaysPlayIdActsActIdScenesNewRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesNewRoute
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute: typeof AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedSpecializationsSpecializationIdRoute:
    AuthenticatedSpecializationsSpecializationIdRoute,
  AuthenticatedSpecializationsNewRoute: AuthenticatedSpecializationsNewRoute,
  AuthenticatedTheatersNewRoute: AuthenticatedTheatersNewRoute,
  AuthenticatedAuthorsIndexRoute: AuthenticatedAuthorsIndexRoute,
  AuthenticatedPlaysIndexRoute: AuthenticatedPlaysIndexRoute,
  AuthenticatedProductionsIndexRoute: AuthenticatedProductionsIndexRoute,
  AuthenticatedSpacesIndexRoute: AuthenticatedSpacesIndexRoute,
  AuthenticatedSpecializationsIndexRoute:
    AuthenticatedSpecializationsIndexRoute,
  AuthenticatedTheatersIndexRoute: AuthenticatedTheatersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedPlaysPlayIdPartScriptsRoute:
    AuthenticatedPlaysPlayIdPartScriptsRoute,
  AuthenticatedPlaysPlayIdScriptRoute: AuthenticatedPlaysPlayIdScriptRoute,
  AuthenticatedPlaysPlayIdWordCloudsRoute:
    AuthenticatedPlaysPlayIdWordCloudsRoute,
  AuthenticatedProductionsProductionIdDoublingChartsRoute:
    AuthenticatedProductionsProductionIdDoublingChartsRoute,
  AuthenticatedProductionsProductionIdRehearsalsRoute:
    AuthenticatedProductionsProductionIdRehearsalsRoute,
  AuthenticatedProductionsProductionIdSetDesignRoute:
    AuthenticatedProductionsProductionIdSetDesignRoute,
  AuthenticatedAuthorsAuthorIdIndexRoute:
    AuthenticatedAuthorsAuthorIdIndexRoute,
  AuthenticatedPlaysPlayIdIndexRoute: AuthenticatedPlaysPlayIdIndexRoute,
  AuthenticatedProductionsProductionIdIndexRoute:
    AuthenticatedProductionsProductionIdIndexRoute,
  AuthenticatedSpacesSpaceIdIndexRoute: AuthenticatedSpacesSpaceIdIndexRoute,
  AuthenticatedTheatersTheaterIdIndexRoute:
    AuthenticatedTheatersTheaterIdIndexRoute,
  AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
  AuthenticatedPlaysPlayIdActsActIdIndexRoute:
    AuthenticatedPlaysPlayIdActsActIdIndexRoute,
  AuthenticatedPlaysPlayIdActsActIdScenesNewRoute:
    AuthenticatedPlaysPlayIdActsActIdScenesNewRoute,
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute:
    AuthenticatedPlaysPlayIdActsActIdScenesSceneIdIndexRoute,
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute:
    AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesNewRoute,
  AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute:
    AuthenticatedPlaysPlayIdActsActIdScenesSceneIdFrenchScenesFrenchSceneIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicFaqRoute: typeof PublicFaqRoute
  PublicGettingStartedRoute: typeof PublicGettingStartedRoute
  PublicHelpRoute: typeof PublicHelpRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFaqRoute: PublicFaqRoute,
  PublicGettingStartedRoute: PublicGettingStartedRoute,
  PublicHelpRoute: PublicHelpRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface FreeRouteChildren {
  FreeCastingRoute: typeof FreeCastingRoute
  FreeCutRoute: typeof FreeCutRoute
  FreeDoublingRoute: typeof FreeDoublingRoute
  FreePartScriptsRoute: typeof FreePartScriptsRoute
  FreeWordCloudRoute: typeof FreeWordCloudRoute
  FreeIndexRoute: typeof FreeIndexRoute
}

const FreeRouteChildren: FreeRouteChildren = {
  FreeCastingRoute: FreeCastingRoute,
  FreeCutRoute: FreeCutRoute,
  FreeDoublingRoute: FreeDoublingRoute,
  FreePartScriptsRoute: FreePartScriptsRoute,
  FreeWordCloudRoute: FreeWordCloudRoute,
  FreeIndexRoute: FreeIndexRoute,
}

const FreeRouteWithChildren = FreeRoute._addFileChildren(FreeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AboutRoute: AboutRoute,
  FreeRoute: FreeRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
